export const tr = {
  loading: 'Yükleniyor',
  signInToTChat: 'SERÇE\'ye Giriş Yap',
  createYourAccount: 'Hesabını Oluştur',
  signIn: 'Giriş Yap',
  signUp: 'Kayıt Ol',
  emailAddress: 'E-posta Adresi',
  password: 'Şifre',
  checkYourEmail: 'Doğrulama için e-postanızı kontrol edin.',
  dontHaveAccount: 'Hesabın yok mu? Kayıt Ol',
  alreadyHaveAccount: 'Zaten bir hesabın var mı? Giriş Yap',
  welcomeBack: 'Tekrar Hoş Geldin',
  signInToContinue: 'Devam etmek için giriş yap.',
  joinTheCommunity: 'Topluluğa katılmak için bir hesap oluştur.',
  errorLoadingMessages: 'Mesajlar yüklenirken bir hata oluştu.',
  welcomeToChannel: '#{channelName} kanalına hoş geldin!',
  startOfChannel: 'Burası #{channelName} kanalının başlangıcı.',
  messagePlaceholder: '#{channelName} kanalına mesaj gönder',
  connectionError: 'Bağlantı Hatası',
  connectionErrorDescription: 'Ses kanalına bağlanırken bir sorun oluştu. Lütfen ağ bağlantınızı ve mikrofon/kamera izinlerinizi kontrol edip tekrar deneyin.',
  connectingToVoice: 'Ses kanalına bağlanılıyor...',
  connecting: 'Bağlanılıyor',
  joinVoice: 'Sese Katıl',
  usernameCannotBeEmpty: 'Kullanıcı adı boş olamaz.',
  usernameTaken: 'Bu kullanıcı adı zaten alınmış.',
  setUpYourProfile: 'Profilini Ayarla',
  chooseUsernameAndAvatar: 'Bir kullanıcı adı ve avatar seçerek başla.',
  username: 'Kullanıcı Adı',
  chooseAvatar: 'Avatar Seç',
  gender: 'Cinsiyet',
  preferNotToSay: 'Belirtmek İstemiyorum',
  male: 'Erkek',
  female: 'Kadın',
  other: 'Diğer',
  saving: 'Kaydediliyor',
  completeSetup: 'Kurulumu Tamamla',
  userSettings: 'Kullanıcı Ayarları',
  myAccount: 'Hesabım',
  voiceAndVideo: 'Ses ve Görüntü',
  appearance: 'Görünüm', // YENİ
  closeSettings: 'Ayarları Kapat',
  profileUpdated: 'Profil başarıyla güncellendi!',
  reset: 'Sıfırla',
  saveChanges: 'Değişiklikleri Kaydet',
  inputDevice: 'Giriş Cihazı',
  default: 'Varsayılan',
  camera: 'Kamera',
  micTest: 'Mikrofon Testi',
  stopTest: 'Testi Durdur',
  testMic: 'Mikrofonu Dene',
  micTestDescription: 'Konuşurken çubuğun hareket ettiğini görmelisin.',
  detectDevices: 'Cihazları tekrar algıla',
  joinVoiceChannel: 'Ses Kanalına Katıl',
  confirmJoinVoice: '#{channelName} kanalına katılmak istediğinize emin misiniz?',
  cancel: 'İptal',
  joinChannel: 'Kanala Katıl',
  inviteFriendsToServer: '{serverName} sunucusuna arkadaş davet et',
  yourInviteLinkInfo: 'Davet bağlantını arkadaşlarınla paylaşarak onların sunucuna katılmasını sağla!',
  inviteLink: 'Davet Bağlantısı',
  copied: 'Kopyalandı!',
  copy: 'Kopyala',
  serverOverview: 'Genel Bakış',
  members: 'Üyeler',
  serverName: 'Sunucu Adı',
  kickUserConfirmation: '{username} kullanıcısını sunucudan atmak istediğinize emin misiniz?',
  kick: 'At',
  friends: 'Arkadaşlar',
  allFriends: 'Tüm Arkadaşlar',
  pending: 'Bekleyenler',
  addFriend: 'Arkadaş Ekle',
  noFriendsYet: 'Henüz hiç arkadaşın yok. "Arkadaş Ekle" butonuyla yeni arkadaşlar ekleyebilirsin.',
  noPendingRequests: 'Bekleyen arkadaşlık isteği yok.',
  incomingRequest: 'Gelen Arkadaşlık İsteği',
  addFriendDescription: 'Arkadaşını kullanıcı adıyla ekleyebilirsin. Büyük/küçük harf duyarlıdır!',
  enterUsername: 'Kullanıcı adı gir...',
  sending: 'Gönderiliyor',
  sendRequest: 'İstek Gönder',
  signOut: 'Çıkış Yap',
  profilePreview: 'Profil Önizlemesi',
  accountSettings: 'Hesap Ayarları',
  voiceSettings: 'Ses Ayarları',
  videoSettings: 'Görüntü Ayarları',
  invite: 'Davet Et',
  invited: 'Davet Edildi',
  noFriendsToInvite: 'Davet edilecek arkadaş bulunamadı.',
  noFriendsToInviteDescription: 'Bu sunucuda olmayan arkadaşların burada görünecektir.',
  serverInvites: 'Sunucu Davetleri',
  from: 'davet eden',
  accept: 'Kabul Et',
  decline: 'Reddet',
  noServerInvites: 'Bekleyen sunucu davetin yok.',
  invitePeople: 'İnsanları Davet Et',
  createServer: 'Sunucu Oluştur',
  createChannel: 'Kanal Oluştur',
  serverSettings: 'Sunucu Ayarları',
  openCamera: 'Kamerayı Aç',
  closeCamera: 'Kamerayı Kapat',
  shareScreen: 'Ekranı Paylaş',
  stopSharing: 'Paylaşımı Durdur',
  discoverServers: 'Sunucuları Keşfet',
  discoverDescription: 'Katılabileceğin yeni topluluklar bul.',
  join: 'Katıl',
  joining: 'Katılıyor...',
  joined: 'Katıldın',
  friendsServers: 'Arkadaş Sunucuları',
  publicServers: 'Genel Sunucular',
  requestSent: 'İstek Gönderildi',
  joinServer: 'Sunucuya Katıl',
  serverVisibility: 'Sunucu Görünürlüğü',
  publicDesc: 'Herkesin Keşfet sayfasında görebileceği sunucu.',
  privateDesc: 'Sadece davet edilenlerin katılabileceği sunucu.',
  joinApproval: 'Katılım Onayı',
  requireApproval: 'Yeni üyeler için onay gereksin.',
  joinRequests: 'Katılma İstekleri',
  wantsToJoin: '{username}, {serverName} sunucusuna katılmak istiyor.',
  requestToJoin: 'Katılma İsteği',
  approve: 'Onayla',
  approveSelected: 'Seçilenleri Onayla',
  declineSelected: 'Seçilenleri Reddet',
  selectAll: 'Tümünü Seç',
};